spring:
  # spring datasource configuration 的配置
  datasource:
    driver-class-name: org.h2.Driver
    username: 'sa'
    password: 'sa'
    url: 'jdbc:h2:mem:mycurrencydb' 
  h2:
    console:
      enabled: true 
      path: '/h2-console' 
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update  
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html